$base = rgb(1a1b26)
$text = rgb(c0caf5)
$surface0 = rgb(3b4261)
$surface1 = rgb(414868)
$overlay0 = rgb(565f89)
$blue = rgb(7aa2f7)
$red = rgb(f7768e)
$green = rgb(9ece6a)

background {
    monitor =
    path = /home/init0/.config/backgrounds/021.jpg
    color = $base
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $surface0
    inner_color = $surface1
    font_color = $text
    fade_on_empty = false
    placeholder_text = <i><span foreground="##c0caf5">Password...</span></i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
    check_color = $blue
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $red
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text
    font_size = 120
    font_family = Hack Nerd Font Bold
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, Mercyyy!
    color = $text
    font_size = 20
    font_family = Hack Nerd Font
    position = 0, -50
    halign = center
    valign = center
}
