exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME DISPLAY XDG_SESSION_TYPE GDK_BACKEND QT_QPA_PLATFORM
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME DISPLAY XDG_SESSION_TYPE GDK_BACKEND QT_QPA_PLATFORM
exec systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk

exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec /usr/libexec/polkit-gnome-authentication-agent-1

# UI Components (with slight delay to ensure environment is ready)
exec_always pkill swayosd-server || true
exec_always pkill waybar || true
exec_always pkill autotiling || true
exec_always sleep 0.5 && swayosd-server -s /home/init0/.config/swayosd/style.css &
exec_always sleep 0.5 && waybar &
exec_always sleep 0.5 && ~/.local/bin/autotiling &

exec_always bash $HOME/.config/sway/scripts/idle.sh
exec --no-startup-id udiskie &
