gaps inner 7
gaps outer 4
default_border pixel 2
default_floating_border pixel 2
smart_borders on
hide_edge_borders smart
titlebar_border_thickness 0
focus_follows_mouse no
for_window [all] title_format " "
for_window [all] title_window_icon none
font pango:Hack Nerd Font 10

exec_always {
    gsettings set org.gnome.desktop.interface gtk-decoration-layout ":close"
    gsettings set org.gnome.desktop.interface cursor-theme 'Catppuccin-Mocha-Dark-Cursors'
    gsettings set $gnome-schema gtk-theme 'adw-gtk3-dark'
    gsettings set $gnome-schema icon-theme 'Papirus-Dark'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
}

seat * xcursor_theme Catppuccin-Mocha-Dark-Cursors 20

client.focused           $blue     $base        $text      $blue      $blue
client.focused_inactive  $mantle   $base        $text      $mantle    $mantle
client.unfocused         $mantle   $base        $text      $mantle    $mantle
client.urgent            $peach    $base        $peach     $overlay0  $peach
client.placeholder       $base     $base        $text      $overlay0  $overlay0
client.background        $base

for_window [class="Yad" instance="yad"] floating enable
for_window [app_id="yad"] floating enable
for_window [app_id="blueman-manager"] floating enable, resize set width 40 ppt height 40 ppt
for_window [app_id="file-roller"] floating enable
for_window [class="Xsane" instance="xsane"] floating enable
for_window [app_id="pavucontrol" ] floating enable, resize set width 30 ppt height 40 ppt
for_window [class="qt5ct" instance="qt5ct"] floating enable, resize set width 60 ppt height 50 ppt
for_window [class="Bluetooth-sendto" instance="bluetooth-sendto"] floating enable
for_window [app_id="pamac-manager"] floating enable, resize set width 80 ppt height 70 ppt
for_window [class="Lxappearance"] floating enable, resize set width 60 ppt height 50 ppt
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [window_role="About"] floating enable
for_window [title="File Operation Progress"] floating enable, border pixel 1, sticky enable, resize set width 40 ppt height 30 ppt
for_window [title="nmtui"] floating enable, resize set width 50 ppt height 70 ppt
for_window [app_id="xsensors"] floating enable
for_window [title="Save File"] floating enable
for_window [title="Floating Window - Show Me The Key"] floating enable, sticky enable
for_window [title="Picture in picture"] floating enable, sticky enable
for_window [class="Brave-browser"] inhibit_idle fullscreen
for_window [app_id="Chromium"] inhibit_idle fullscreen
